// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "product-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// ProductServiceInterface is an autogenerated mock type for the ProductServiceInterface type
type ProductServiceInterface struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, product
func (_m *ProductServiceInterface) CreateProduct(ctx context.Context, product entity.ProductEntity) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ProductEntity) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProductByID provides a mock function with given fields: ctx, productID
func (_m *ProductServiceInterface) DeleteProductByID(ctx context.Context, productID int64) error {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllProducts provides a mock function with given fields: ctx, query
func (_m *ProductServiceInterface) GetAllProducts(ctx context.Context, query entity.QueryStringProduct) ([]entity.ProductEntity, int64, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []entity.ProductEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringProduct) ([]entity.ProductEntity, int64, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringProduct) []entity.ProductEntity); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringProduct) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringProduct) int64); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringProduct) error); ok {
		r3 = rf(ctx, query)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetHomeProducts provides a mock function with given fields: ctx, limit
func (_m *ProductServiceInterface) GetHomeProducts(ctx context.Context, limit int) ([]entity.ProductEntity, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetHomeProducts")
	}

	var r0 []entity.ProductEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.ProductEntity, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.ProductEntity); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, productID
func (_m *ProductServiceInterface) GetProductByID(ctx context.Context, productID int64) (*entity.ProductEntity, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *entity.ProductEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.ProductEntity, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.ProductEntity); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchProducts provides a mock function with given fields: ctx, query
func (_m *ProductServiceInterface) SearchProducts(ctx context.Context, query entity.QueryStringProduct) ([]entity.ProductEntity, int64, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchProducts")
	}

	var r0 []entity.ProductEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringProduct) ([]entity.ProductEntity, int64, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringProduct) []entity.ProductEntity); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringProduct) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringProduct) int64); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringProduct) error); ok {
		r3 = rf(ctx, query)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// UpdateProduct provides a mock function with given fields: ctx, product
func (_m *ProductServiceInterface) UpdateProduct(ctx context.Context, product entity.ProductEntity) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ProductEntity) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductServiceInterface creates a new instance of ProductServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductServiceInterface {
	mock := &ProductServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
