### POST signin
POST http://localhost:8080/signin
Content-Type: application/json

{
  "email": "superadmin@mail.com",
  "password": "rahasia"
}

> {% client.global.set("X-API-TOKEN", response.body.data.access_token); %}

### check middleware
GET http://localhost:8080/admin/customers
Authorization: Bearer {{X-API-TOKEN}}
