@baseUrl = http://localhost:8080
### POST signin
POST {{baseUrl}}/signin
Content-Type: application/json

{
  "email": "superadmin@mail.com",
  "password": "rahasia"
}

> {% client.global.set("X-API-TOKEN", response.body.data.access_token); %}

### check middleware
GET {{baseUrl}}/admin/customers
Authorization: Bearer {{X-API-TOKEN}}

### update users
PUT {{baseUrl}}/auth/profile
Authorization: Bearer {{X-API-TOKEN}}
Content-Type: application/json

{
    "email": "jgunawan30052@gmail.com",
    "password": "rahasia",
    "name": "Jonathan Gunawan",
    "phone": "081234567890",
    "address": "Jl. Medan Merdeka Selatan No. 8, Gambir, Jakarta Pusat",
    "lat": "-6.1818",
    "lng": "106.8223",
    "photo": "https://google.com"
}

### get users profile
GET {{baseUrl}}/auth/profile
Authorization: Bearer {{X-API-TOKEN}}
Accept: application/json

### CREATE USER
POST {{baseUrl}}/signup
Accept: application/json
Content-Type: application/json

{
  "name": "jonathan1",
  "email": "jonathan1@mail.com",
  "password": "rahasia",
  "password_confirmation": "rahasia"
}

### FORGOT PASSWORD
POST {{baseUrl}}/forgot-password
Accept: application/json
Content-Type: application/json

{
  "email": "jonathan1@mail.com"
}