// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "notification-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// NotificationService is an autogenerated mock type for the NotificationService type
type NotificationService struct {
	mock.Mock
}

// GetAdmin provides a mock function with no fields
func (_m *NotificationService) GetAdmin() entity.AdminEntity {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAdmin")
	}

	var r0 entity.AdminEntity
	if rf, ok := ret.Get(0).(func() entity.AdminEntity); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(entity.AdminEntity)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, query, userID
func (_m *NotificationService) GetAll(ctx context.Context, query entity.NotifQueryString, userID int64) ([]entity.NotificationEntity, int64, int64, error) {
	ret := _m.Called(ctx, query, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.NotificationEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.NotifQueryString, int64) ([]entity.NotificationEntity, int64, int64, error)); ok {
		return rf(ctx, query, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.NotifQueryString, int64) []entity.NotificationEntity); ok {
		r0 = rf(ctx, query, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.NotificationEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.NotifQueryString, int64) int64); ok {
		r1 = rf(ctx, query, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.NotifQueryString, int64) int64); ok {
		r2 = rf(ctx, query, userID)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.NotifQueryString, int64) error); ok {
		r3 = rf(ctx, query, userID)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetByID provides a mock function with given fields: ctx, notifID, userID
func (_m *NotificationService) GetByID(ctx context.Context, notifID int64, userID int64) (*entity.NotificationEntity, error) {
	ret := _m.Called(ctx, notifID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.NotificationEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*entity.NotificationEntity, error)); ok {
		return rf(ctx, notifID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *entity.NotificationEntity); ok {
		r0 = rf(ctx, notifID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.NotificationEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, notifID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessNotification provides a mock function with given fields: ctx, notif
func (_m *NotificationService) ProcessNotification(ctx context.Context, notif entity.NotificationEntity) error {
	ret := _m.Called(ctx, notif)

	if len(ret) == 0 {
		panic("no return value specified for ProcessNotification")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.NotificationEntity) error); ok {
		r0 = rf(ctx, notif)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadAllNotifications provides a mock function with given fields: ctx, userID
func (_m *NotificationService) ReadAllNotifications(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReadAllNotifications")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadNotificationByID provides a mock function with given fields: ctx, id, userID
func (_m *NotificationService) ReadNotificationByID(ctx context.Context, id int64, userID int64) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReadNotificationByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendEmailNotif provides a mock function with given fields: to, subject, body
func (_m *NotificationService) SendEmailNotif(to string, subject string, body string) error {
	ret := _m.Called(to, subject, body)

	if len(ret) == 0 {
		panic("no return value specified for SendEmailNotif")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(to, subject, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationService creates a new instance of NotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationService {
	mock := &NotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
