// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "notification-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// NotificationRepository is an autogenerated mock type for the NotificationRepository type
type NotificationRepository struct {
	mock.Mock
}

// CreateNotification provides a mock function with given fields: ctx, notification
func (_m *NotificationRepository) CreateNotification(ctx context.Context, notification entity.NotificationEntity) (int64, error) {
	ret := _m.Called(ctx, notification)

	if len(ret) == 0 {
		panic("no return value specified for CreateNotification")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.NotificationEntity) (int64, error)); ok {
		return rf(ctx, notification)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.NotificationEntity) int64); ok {
		r0 = rf(ctx, notification)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.NotificationEntity) error); ok {
		r1 = rf(ctx, notification)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, query, userID
func (_m *NotificationRepository) GetAll(ctx context.Context, query entity.NotifQueryString, userID int64) ([]entity.NotificationEntity, int64, error) {
	ret := _m.Called(ctx, query, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []entity.NotificationEntity
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.NotifQueryString, int64) ([]entity.NotificationEntity, int64, error)); ok {
		return rf(ctx, query, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.NotifQueryString, int64) []entity.NotificationEntity); ok {
		r0 = rf(ctx, query, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.NotificationEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.NotifQueryString, int64) int64); ok {
		r1 = rf(ctx, query, userID)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.NotifQueryString, int64) error); ok {
		r2 = rf(ctx, query, userID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetByID provides a mock function with given fields: ctx, notifID, userID
func (_m *NotificationRepository) GetByID(ctx context.Context, notifID int64, userID int64) (*entity.NotificationEntity, error) {
	ret := _m.Called(ctx, notifID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *entity.NotificationEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*entity.NotificationEntity, error)); ok {
		return rf(ctx, notifID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *entity.NotificationEntity); ok {
		r0 = rf(ctx, notifID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.NotificationEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, notifID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadAllNotifications provides a mock function with given fields: ctx, userID
func (_m *NotificationRepository) ReadAllNotifications(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReadAllNotifications")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReadNotificationByID provides a mock function with given fields: ctx, id, userID
func (_m *NotificationRepository) ReadNotificationByID(ctx context.Context, id int64, userID int64) error {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for ReadNotificationByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatus provides a mock function with given fields: ctx, id, status
func (_m *NotificationRepository) UpdateStatus(ctx context.Context, id int64, status string) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewNotificationRepository creates a new instance of NotificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNotificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *NotificationRepository {
	mock := &NotificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
