// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MidtransClientInterface is an autogenerated mock type for the MidtransClientInterface type
type MidtransClientInterface struct {
	mock.Mock
}

// CreateTransaction provides a mock function with given fields: orderID, amount, customerName, customerEmail
func (_m *MidtransClientInterface) CreateTransaction(orderID string, amount int64, customerName string, customerEmail string) (string, error) {
	ret := _m.Called(orderID, amount, customerName, customerEmail)

	if len(ret) == 0 {
		panic("no return value specified for CreateTransaction")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, int64, string, string) (string, error)); ok {
		return rf(orderID, amount, customerName, customerEmail)
	}
	if rf, ok := ret.Get(0).(func(string, int64, string, string) string); ok {
		r0 = rf(orderID, amount, customerName, customerEmail)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, int64, string, string) error); ok {
		r1 = rf(orderID, amount, customerName, customerEmail)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMidtransClientInterface creates a new instance of MidtransClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMidtransClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MidtransClientInterface {
	mock := &MidtransClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
