// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "payment-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// OrderSnapshotRepositoryInterface is an autogenerated mock type for the OrderSnapshotRepositoryInterface type
type OrderSnapshotRepositoryInterface struct {
	mock.Mock
}

// GetOrderByID provides a mock function with given fields: ctx, orderID
func (_m *OrderSnapshotRepositoryInterface) GetOrderByID(ctx context.Context, orderID int64) (*entity.OrdersSnapshotEntity, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *entity.OrdersSnapshotEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.OrdersSnapshotEntity, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.OrdersSnapshotEntity); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OrdersSnapshotEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByOrderCode provides a mock function with given fields: ctx, orderCode
func (_m *OrderSnapshotRepositoryInterface) GetOrderByOrderCode(ctx context.Context, orderCode string) (*entity.OrdersSnapshotEntity, error) {
	ret := _m.Called(ctx, orderCode)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByOrderCode")
	}

	var r0 *entity.OrdersSnapshotEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.OrdersSnapshotEntity, error)); ok {
		return rf(ctx, orderCode)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.OrdersSnapshotEntity); ok {
		r0 = rf(ctx, orderCode)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OrdersSnapshotEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderCode)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, order
func (_m *OrderSnapshotRepositoryInterface) Upsert(ctx context.Context, order entity.OrdersSnapshotEntity) error {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrdersSnapshotEntity) error); ok {
		r0 = rf(ctx, order)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderSnapshotRepositoryInterface creates a new instance of OrderSnapshotRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderSnapshotRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderSnapshotRepositoryInterface {
	mock := &OrderSnapshotRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
