// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "payment-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// PaymentServiceInterface is an autogenerated mock type for the PaymentServiceInterface type
type PaymentServiceInterface struct {
	mock.Mock
}

// GetAllPayments provides a mock function with given fields: ctx, req
func (_m *PaymentServiceInterface) GetAllPayments(ctx context.Context, req entity.PaymentQueryStringRequest) ([]entity.PaymentEntity, int64, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPayments")
	}

	var r0 []entity.PaymentEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaymentQueryStringRequest) ([]entity.PaymentEntity, int64, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaymentQueryStringRequest) []entity.PaymentEntity); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PaymentEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.PaymentQueryStringRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.PaymentQueryStringRequest) int64); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.PaymentQueryStringRequest) error); ok {
		r3 = rf(ctx, req)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetPaymentDetail provides a mock function with given fields: ctx, paymentID, userID
func (_m *PaymentServiceInterface) GetPaymentDetail(ctx context.Context, paymentID int64, userID int64) (*entity.PaymentEntity, error) {
	ret := _m.Called(ctx, paymentID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentDetail")
	}

	var r0 *entity.PaymentEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*entity.PaymentEntity, error)); ok {
		return rf(ctx, paymentID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *entity.PaymentEntity); ok {
		r0 = rf(ctx, paymentID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PaymentEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, paymentID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProcessPayment provides a mock function with given fields: ctx, payment
func (_m *PaymentServiceInterface) ProcessPayment(ctx context.Context, payment entity.PaymentEntity) (*entity.PaymentEntity, error) {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for ProcessPayment")
	}

	var r0 *entity.PaymentEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaymentEntity) (*entity.PaymentEntity, error)); ok {
		return rf(ctx, payment)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaymentEntity) *entity.PaymentEntity); ok {
		r0 = rf(ctx, payment)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PaymentEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.PaymentEntity) error); ok {
		r1 = rf(ctx, payment)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusByOrderCode provides a mock function with given fields: ctx, orderCode, status
func (_m *PaymentServiceInterface) UpdateStatusByOrderCode(ctx context.Context, orderCode string, status string) error {
	ret := _m.Called(ctx, orderCode, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusByOrderCode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, orderCode, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyMidtransSignature provides a mock function with given fields: orderID, statusCode, grossAmount, incomingSignature
func (_m *PaymentServiceInterface) VerifyMidtransSignature(orderID string, statusCode string, grossAmount string, incomingSignature string) bool {
	ret := _m.Called(orderID, statusCode, grossAmount, incomingSignature)

	if len(ret) == 0 {
		panic("no return value specified for VerifyMidtransSignature")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string, string, string, string) bool); ok {
		r0 = rf(orderID, statusCode, grossAmount, incomingSignature)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewPaymentServiceInterface creates a new instance of PaymentServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentServiceInterface {
	mock := &PaymentServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
