// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// PaymentHandlerInterface is an autogenerated mock type for the PaymentHandlerInterface type
type PaymentHandlerInterface struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: c
func (_m *PaymentHandlerInterface) CreatePayment(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPayments provides a mock function with given fields: c
func (_m *PaymentHandlerInterface) GetAllPayments(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPayments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetPaymentDetail provides a mock function with given fields: c
func (_m *PaymentHandlerInterface) GetPaymentDetail(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentDetail")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MidtransWebHook provides a mock function with given fields: c
func (_m *PaymentHandlerInterface) MidtransWebHook(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for MidtransWebHook")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentHandlerInterface creates a new instance of PaymentHandlerInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentHandlerInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentHandlerInterface {
	mock := &PaymentHandlerInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
