// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "payment-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// PaymentRepositoryInterface is an autogenerated mock type for the PaymentRepositoryInterface type
type PaymentRepositoryInterface struct {
	mock.Mock
}

// CreatePayment provides a mock function with given fields: ctx, payment
func (_m *PaymentRepositoryInterface) CreatePayment(ctx context.Context, payment entity.PaymentEntity) error {
	ret := _m.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for CreatePayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaymentEntity) error); ok {
		r0 = rf(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllPayment provides a mock function with given fields: ctx, req
func (_m *PaymentRepositoryInterface) GetAllPayment(ctx context.Context, req entity.PaymentQueryStringRequest) ([]entity.PaymentEntity, int64, int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPayment")
	}

	var r0 []entity.PaymentEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaymentQueryStringRequest) ([]entity.PaymentEntity, int64, int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.PaymentQueryStringRequest) []entity.PaymentEntity); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.PaymentEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.PaymentQueryStringRequest) int64); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.PaymentQueryStringRequest) int64); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.PaymentQueryStringRequest) error); ok {
		r3 = rf(ctx, req)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetPaymentDetail provides a mock function with given fields: ctx, paymentID, filterUserID
func (_m *PaymentRepositoryInterface) GetPaymentDetail(ctx context.Context, paymentID int64, filterUserID int64) (*entity.PaymentEntity, error) {
	ret := _m.Called(ctx, paymentID, filterUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetPaymentDetail")
	}

	var r0 *entity.PaymentEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) (*entity.PaymentEntity, error)); ok {
		return rf(ctx, paymentID, filterUserID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) *entity.PaymentEntity); ok {
		r0 = rf(ctx, paymentID, filterUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.PaymentEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64) error); ok {
		r1 = rf(ctx, paymentID, filterUserID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LogPayment provides a mock function with given fields: ctx, paymentID, status
func (_m *PaymentRepositoryInterface) LogPayment(ctx context.Context, paymentID int64, status string) error {
	ret := _m.Called(ctx, paymentID, status)

	if len(ret) == 0 {
		panic("no return value specified for LogPayment")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, paymentID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusByID provides a mock function with given fields: ctx, orderID, status
func (_m *PaymentRepositoryInterface) UpdateStatusByID(ctx context.Context, orderID int64, status string) error {
	ret := _m.Called(ctx, orderID, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, orderID, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewPaymentRepositoryInterface creates a new instance of PaymentRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPaymentRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PaymentRepositoryInterface {
	mock := &PaymentRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
