ALTER TABLE orders ADD COLUMN IF NOT EXISTS buyer_name VARCHAR(255) DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS buyer_email VARCHAR(255) DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS buyer_phone VARCHAR(17) DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS buyer_address TEXT DEFAULT '';