// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "order-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// ElasticRepositoryInterface is an autogenerated mock type for the ElasticRepositoryInterface type
type ElasticRepositoryInterface struct {
	mock.Mock
}

// SearchOrderElastic provides a mock function with given fields: ctx, q
func (_m *ElasticRepositoryInterface) SearchOrderElastic(ctx context.Context, q entity.QueryStringEntity) ([]entity.OrderEntity, int64, int64, error) {
	ret := _m.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for SearchOrderElastic")
	}

	var r0 []entity.OrderEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringEntity) ([]entity.OrderEntity, int64, int64, error)); ok {
		return rf(ctx, q)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringEntity) []entity.OrderEntity); ok {
		r0 = rf(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringEntity) int64); ok {
		r1 = rf(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringEntity) int64); ok {
		r2 = rf(ctx, q)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringEntity) error); ok {
		r3 = rf(ctx, q)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewElasticRepositoryInterface creates a new instance of ElasticRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewElasticRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ElasticRepositoryInterface {
	mock := &ElasticRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
