// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "order-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// OrderRepositoryInterface is an autogenerated mock type for the OrderRepositoryInterface type
type OrderRepositoryInterface struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, req
func (_m *OrderRepositoryInterface) CreateOrder(ctx context.Context, req entity.OrderEntity) (int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderEntity) (int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderEntity) int64); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.OrderEntity) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllOrders provides a mock function with given fields: ctx, query
func (_m *OrderRepositoryInterface) GetAllOrders(ctx context.Context, query entity.QueryStringEntity) ([]entity.OrderEntity, int64, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []entity.OrderEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringEntity) ([]entity.OrderEntity, int64, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringEntity) []entity.OrderEntity); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringEntity) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringEntity) int64); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringEntity) error); ok {
		r3 = rf(ctx, query)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetOrderByID provides a mock function with given fields: ctx, orderID
func (_m *OrderRepositoryInterface) GetOrderByID(ctx context.Context, orderID int64) (*entity.OrderEntity, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *entity.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.OrderEntity, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.OrderEntity); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByOrderCode provides a mock function with given fields: ctx, code
func (_m *OrderRepositoryInterface) GetOrderByOrderCode(ctx context.Context, code string) (*entity.OrderEntity, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByOrderCode")
	}

	var r0 *entity.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.OrderEntity, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.OrderEntity); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdatePaymentMethod provides a mock function with given fields: ctx, orderID, paymentMethod
func (_m *OrderRepositoryInterface) UpdatePaymentMethod(ctx context.Context, orderID int64, paymentMethod string) error {
	ret := _m.Called(ctx, orderID, paymentMethod)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePaymentMethod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string) error); ok {
		r0 = rf(ctx, orderID, paymentMethod)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateStatusOrder provides a mock function with given fields: ctx, req
func (_m *OrderRepositoryInterface) UpdateStatusOrder(ctx context.Context, req entity.OrderEntity) (int64, string, string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusOrder")
	}

	var r0 int64
	var r1 string
	var r2 string
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderEntity) (int64, string, string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderEntity) int64); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.OrderEntity) string); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.OrderEntity) string); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Get(2).(string)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.OrderEntity) error); ok {
		r3 = rf(ctx, req)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// NewOrderRepositoryInterface creates a new instance of OrderRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepositoryInterface {
	mock := &OrderRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
