// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"
	mock "github.com/stretchr/testify/mock"
)

// MiddlewareAdapter is an autogenerated mock type for the MiddlewareAdapter type
type MiddlewareAdapter struct {
	mock.Mock
}

// CheckToken provides a mock function with given fields: secretKey
func (_m *MiddlewareAdapter) CheckToken(secretKey string) echo.MiddlewareFunc {
	ret := _m.Called(secretKey)

	if len(ret) == 0 {
		panic("no return value specified for CheckToken")
	}

	var r0 echo.MiddlewareFunc
	if rf, ok := ret.Get(0).(func(string) echo.MiddlewareFunc); ok {
		r0 = rf(secretKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(echo.MiddlewareFunc)
		}
	}

	return r0
}

// NewMiddlewareAdapter creates a new instance of MiddlewareAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiddlewareAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MiddlewareAdapter {
	mock := &MiddlewareAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
