// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "user-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// VerificationTokenRepositoryInterface is an autogenerated mock type for the VerificationTokenRepositoryInterface type
type VerificationTokenRepositoryInterface struct {
	mock.Mock
}

// CreateVerificationToken provides a mock function with given fields: ctx, verificationToken
func (_m *VerificationTokenRepositoryInterface) CreateVerificationToken(ctx context.Context, verificationToken entity.VerificationTokenEntity) error {
	ret := _m.Called(ctx, verificationToken)

	if len(ret) == 0 {
		panic("no return value specified for CreateVerificationToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.VerificationTokenEntity) error); ok {
		r0 = rf(ctx, verificationToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetDataByToken provides a mock function with given fields: ctx, token
func (_m *VerificationTokenRepositoryInterface) GetDataByToken(ctx context.Context, token string) (*entity.VerificationTokenEntity, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetDataByToken")
	}

	var r0 *entity.VerificationTokenEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.VerificationTokenEntity, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.VerificationTokenEntity); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.VerificationTokenEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVerificationTokenRepositoryInterface creates a new instance of VerificationTokenRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVerificationTokenRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *VerificationTokenRepositoryInterface {
	mock := &VerificationTokenRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
