// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// SupabaseInterface is an autogenerated mock type for the SupabaseInterface type
type SupabaseInterface struct {
	mock.Mock
}

// RemoveFile provides a mock function with given fields: path
func (_m *SupabaseInterface) RemoveFile(path string) error {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UploadFile provides a mock function with given fields: path, file, contentType
func (_m *SupabaseInterface) UploadFile(path string, file io.Reader, contentType string) (string, error) {
	ret := _m.Called(path, file, contentType)

	if len(ret) == 0 {
		panic("no return value specified for UploadFile")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, io.Reader, string) (string, error)); ok {
		return rf(path, file, contentType)
	}
	if rf, ok := ret.Get(0).(func(string, io.Reader, string) string); ok {
		r0 = rf(path, file, contentType)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, io.Reader, string) error); ok {
		r1 = rf(path, file, contentType)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSupabaseInterface creates a new instance of SupabaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSupabaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SupabaseInterface {
	mock := &SupabaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
