// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// ImageServiceInterface is an autogenerated mock type for the ImageServiceInterface type
type ImageServiceInterface struct {
	mock.Mock
}

// UploadProfileImage provides a mock function with given fields: file
func (_m *ImageServiceInterface) UploadProfileImage(file *multipart.FileHeader) (string, error) {
	ret := _m.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for UploadProfileImage")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader) (string, error)); ok {
		return rf(file)
	}
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader) string); ok {
		r0 = rf(file)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(*multipart.FileHeader) error); ok {
		r1 = rf(file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewImageServiceInterface creates a new instance of ImageServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageServiceInterface {
	mock := &ImageServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
