// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "user-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// RoleRepositoryInterface is an autogenerated mock type for the RoleRepositoryInterface type
type RoleRepositoryInterface struct {
	mock.Mock
}

// CreateRole provides a mock function with given fields: ctx, role
func (_m *RoleRepositoryInterface) CreateRole(ctx context.Context, role entity.RoleEntity) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for CreateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.RoleEntity) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteRoleByID provides a mock function with given fields: ctx, id
func (_m *RoleRepositoryInterface) DeleteRoleByID(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoleByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllRole provides a mock function with given fields: ctx, search
func (_m *RoleRepositoryInterface) GetAllRole(ctx context.Context, search string) ([]entity.RoleEntity, error) {
	ret := _m.Called(ctx, search)

	if len(ret) == 0 {
		panic("no return value specified for GetAllRole")
	}

	var r0 []entity.RoleEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]entity.RoleEntity, error)); ok {
		return rf(ctx, search)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []entity.RoleEntity); ok {
		r0 = rf(ctx, search)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.RoleEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, search)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRoleByID provides a mock function with given fields: ctx, id
func (_m *RoleRepositoryInterface) GetRoleByID(ctx context.Context, id int64) (*entity.RoleEntity, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetRoleByID")
	}

	var r0 *entity.RoleEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.RoleEntity, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.RoleEntity); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.RoleEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateRole provides a mock function with given fields: ctx, role
func (_m *RoleRepositoryInterface) UpdateRole(ctx context.Context, role entity.RoleEntity) error {
	ret := _m.Called(ctx, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.RoleEntity) error); ok {
		r0 = rf(ctx, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRoleRepositoryInterface creates a new instance of RoleRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRoleRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *RoleRepositoryInterface {
	mock := &RoleRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
