// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	echo "github.com/labstack/echo/v4"

	mock "github.com/stretchr/testify/mock"
)

// UploadImageInterface is an autogenerated mock type for the UploadImageInterface type
type UploadImageInterface struct {
	mock.Mock
}

// UploadImage provides a mock function with given fields: c
func (_m *UploadImageInterface) UploadImage(c echo.Context) error {
	ret := _m.Called(c)

	if len(ret) == 0 {
		panic("no return value specified for UploadImage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(echo.Context) error); ok {
		r0 = rf(c)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUploadImageInterface creates a new instance of UploadImageInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUploadImageInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UploadImageInterface {
	mock := &UploadImageInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
