// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "user-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserServiceInterface is an autogenerated mock type for the UserServiceInterface type
type UserServiceInterface struct {
	mock.Mock
}

// CreateCustomer provides a mock function with given fields: ctx, user
func (_m *UserServiceInterface) CreateCustomer(ctx context.Context, user entity.UserEntity) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserEntity) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateUserAccount provides a mock function with given fields: ctx, user
func (_m *UserServiceInterface) CreateUserAccount(ctx context.Context, user entity.UserEntity) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserAccount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserEntity) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCustomer provides a mock function with given fields: ctx, customerID
func (_m *UserServiceInterface) DeleteCustomer(ctx context.Context, customerID int64) error {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ForgotPassword provides a mock function with given fields: ctx, user
func (_m *UserServiceInterface) ForgotPassword(ctx context.Context, user entity.UserEntity) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for ForgotPassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserEntity) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCustomers provides a mock function with given fields: ctx, query
func (_m *UserServiceInterface) GetAllCustomers(ctx context.Context, query entity.QueryStringCustomer) ([]entity.UserEntity, int64, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCustomers")
	}

	var r0 []entity.UserEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringCustomer) ([]entity.UserEntity, int64, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringCustomer) []entity.UserEntity); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.UserEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringCustomer) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringCustomer) int64); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringCustomer) error); ok {
		r3 = rf(ctx, query)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetCustomerByID provides a mock function with given fields: ctx, userID
func (_m *UserServiceInterface) GetCustomerByID(ctx context.Context, userID int64) (*entity.UserEntity, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerByID")
	}

	var r0 *entity.UserEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.UserEntity, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.UserEntity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserProfile provides a mock function with given fields: ctx, userID
func (_m *UserServiceInterface) GetUserProfile(ctx context.Context, userID int64) (*entity.UserEntity, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserProfile")
	}

	var r0 *entity.UserEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.UserEntity, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.UserEntity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SignIn provides a mock function with given fields: ctx, req
func (_m *UserServiceInterface) SignIn(ctx context.Context, req entity.UserEntity) (*entity.UserEntity, string, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 *entity.UserEntity
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserEntity) (*entity.UserEntity, string, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserEntity) *entity.UserEntity); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.UserEntity) string); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.UserEntity) error); ok {
		r2 = rf(ctx, req)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// SignOut provides a mock function with given fields: ctx, userID
func (_m *UserServiceInterface) SignOut(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SignOut")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateCustomer provides a mock function with given fields: ctx, user
func (_m *UserServiceInterface) UpdateCustomer(ctx context.Context, user entity.UserEntity) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCustomer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserEntity) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateDataUser provides a mock function with given fields: ctx, user
func (_m *UserServiceInterface) UpdateDataUser(ctx context.Context, user entity.UserEntity) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateDataUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserEntity) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdatePassword provides a mock function with given fields: ctx, user
func (_m *UserServiceInterface) UpdatePassword(ctx context.Context, user entity.UserEntity) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserEntity) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateProfilePassword provides a mock function with given fields: ctx, userID, currentPassword, newPassword
func (_m *UserServiceInterface) UpdateProfilePassword(ctx context.Context, userID int64, currentPassword string, newPassword string) error {
	ret := _m.Called(ctx, userID, currentPassword, newPassword)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProfilePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, string) error); ok {
		r0 = rf(ctx, userID, currentPassword, newPassword)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// VerifyToken provides a mock function with given fields: ctx, token
func (_m *UserServiceInterface) VerifyToken(ctx context.Context, token string) (*entity.UserEntity, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *entity.UserEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.UserEntity, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.UserEntity); ok {
		r0 = rf(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserServiceInterface creates a new instance of UserServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserServiceInterface {
	mock := &UserServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
