// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	response "product-service/internal/adapter/handler/response"

	mock "github.com/stretchr/testify/mock"
)

// CartServiceInterface is an autogenerated mock type for the CartServiceInterface type
type CartServiceInterface struct {
	mock.Mock
}

// AddToCart provides a mock function with given fields: ctx, userID, productID, quantity
func (_m *CartServiceInterface) AddToCart(ctx context.Context, userID int64, productID int64, quantity int64) error {
	ret := _m.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for AddToCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) error); ok {
		r0 = rf(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClearCart provides a mock function with given fields: ctx, userID
func (_m *CartServiceInterface) ClearCart(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecreaseItem provides a mock function with given fields: ctx, userID, productID, quantity
func (_m *CartServiceInterface) DecreaseItem(ctx context.Context, userID int64, productID int64, quantity int64) error {
	ret := _m.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) error); ok {
		r0 = rf(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCart provides a mock function with given fields: ctx, userID
func (_m *CartServiceInterface) GetCart(ctx context.Context, userID int64) ([]response.CartResponse, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 []response.CartResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]response.CartResponse, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []response.CartResponse); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]response.CartResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveFromCart provides a mock function with given fields: ctx, userID, productID
func (_m *CartServiceInterface) RemoveFromCart(ctx context.Context, userID int64, productID int64) error {
	ret := _m.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCartServiceInterface creates a new instance of CartServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartServiceInterface {
	mock := &CartServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
