// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "product-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// CartRedisRepositoryInterface is an autogenerated mock type for the CartRedisRepositoryInterface type
type CartRedisRepositoryInterface struct {
	mock.Mock
}

// AddToCart provides a mock function with given fields: ctx, userID, item
func (_m *CartRedisRepositoryInterface) AddToCart(ctx context.Context, userID int64, item entity.CartItem) error {
	ret := _m.Called(ctx, userID, item)

	if len(ret) == 0 {
		panic("no return value specified for AddToCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, entity.CartItem) error); ok {
		r0 = rf(ctx, userID, item)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClearCart provides a mock function with given fields: ctx, userID
func (_m *CartRedisRepositoryInterface) ClearCart(ctx context.Context, userID int64) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ClearCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DecreaseItem provides a mock function with given fields: ctx, userID, productID, quantity
func (_m *CartRedisRepositoryInterface) DecreaseItem(ctx context.Context, userID int64, productID int64, quantity int64) error {
	ret := _m.Called(ctx, userID, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, int64) error); ok {
		r0 = rf(ctx, userID, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetCart provides a mock function with given fields: ctx, userID
func (_m *CartRedisRepositoryInterface) GetCart(ctx context.Context, userID int64) ([]entity.CartItem, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetCart")
	}

	var r0 []entity.CartItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.CartItem, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.CartItem); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CartItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveFromCart provides a mock function with given fields: ctx, userID, productID
func (_m *CartRedisRepositoryInterface) RemoveFromCart(ctx context.Context, userID int64, productID int64) error {
	ret := _m.Called(ctx, userID, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFromCart")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, userID, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCartRedisRepositoryInterface creates a new instance of CartRedisRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCartRedisRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CartRedisRepositoryInterface {
	mock := &CartRedisRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
