// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "product-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// CategoryRepositoryInterface is an autogenerated mock type for the CategoryRepositoryInterface type
type CategoryRepositoryInterface struct {
	mock.Mock
}

// CheckSlugExists provides a mock function with given fields: ctx, slug
func (_m *CategoryRepositoryInterface) CheckSlugExists(ctx context.Context, slug string) (bool, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for CheckSlugExists")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateCategory provides a mock function with given fields: ctx, category
func (_m *CategoryRepositoryInterface) CreateCategory(ctx context.Context, category entity.CategoryEntity) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for CreateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CategoryEntity) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteCategoryByID provides a mock function with given fields: ctx, categoryID
func (_m *CategoryRepositoryInterface) DeleteCategoryByID(ctx context.Context, categoryID int64) error {
	ret := _m.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCategoryByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, categoryID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCategories provides a mock function with given fields: ctx, query
func (_m *CategoryRepositoryInterface) GetAllCategories(ctx context.Context, query entity.QueryStringCategory) ([]entity.CategoryEntity, int64, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCategories")
	}

	var r0 []entity.CategoryEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringCategory) ([]entity.CategoryEntity, int64, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringCategory) []entity.CategoryEntity); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CategoryEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringCategory) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringCategory) int64); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringCategory) error); ok {
		r3 = rf(ctx, query)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetAllPublishedCategories provides a mock function with given fields: ctx
func (_m *CategoryRepositoryInterface) GetAllPublishedCategories(ctx context.Context) ([]entity.CategoryEntity, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAllPublishedCategories")
	}

	var r0 []entity.CategoryEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]entity.CategoryEntity, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []entity.CategoryEntity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.CategoryEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryByID provides a mock function with given fields: ctx, categoryID
func (_m *CategoryRepositoryInterface) GetCategoryByID(ctx context.Context, categoryID int64) (*entity.CategoryEntity, error) {
	ret := _m.Called(ctx, categoryID)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryByID")
	}

	var r0 *entity.CategoryEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.CategoryEntity, error)); ok {
		return rf(ctx, categoryID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.CategoryEntity); ok {
		r0 = rf(ctx, categoryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CategoryEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, categoryID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCategoryBySlug provides a mock function with given fields: ctx, slug
func (_m *CategoryRepositoryInterface) GetCategoryBySlug(ctx context.Context, slug string) (*entity.CategoryEntity, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetCategoryBySlug")
	}

	var r0 *entity.CategoryEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.CategoryEntity, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.CategoryEntity); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.CategoryEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: ctx, category
func (_m *CategoryRepositoryInterface) UpdateCategory(ctx context.Context, category entity.CategoryEntity) error {
	ret := _m.Called(ctx, category)

	if len(ret) == 0 {
		panic("no return value specified for UpdateCategory")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.CategoryEntity) error); ok {
		r0 = rf(ctx, category)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCategoryRepositoryInterface creates a new instance of CategoryRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryRepositoryInterface {
	mock := &CategoryRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
