// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "product-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepositoryInterface is an autogenerated mock type for the ProductRepositoryInterface type
type ProductRepositoryInterface struct {
	mock.Mock
}

// CreateProduct provides a mock function with given fields: ctx, product
func (_m *ProductRepositoryInterface) CreateProduct(ctx context.Context, product entity.ProductEntity) (*entity.ProductEntity, error) {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for CreateProduct")
	}

	var r0 *entity.ProductEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ProductEntity) (*entity.ProductEntity, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ProductEntity) *entity.ProductEntity); ok {
		r0 = rf(ctx, product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ProductEntity) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DecreaseStock provides a mock function with given fields: ctx, productID, quantity
func (_m *ProductRepositoryInterface) DecreaseStock(ctx context.Context, productID int64, quantity int64) error {
	ret := _m.Called(ctx, productID, quantity)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseStock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, productID, quantity)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteProductByID provides a mock function with given fields: ctx, productID
func (_m *ProductRepositoryInterface) DeleteProductByID(ctx context.Context, productID int64) error {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteProductByID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllProducts provides a mock function with given fields: ctx, query
func (_m *ProductRepositoryInterface) GetAllProducts(ctx context.Context, query entity.QueryStringProduct) ([]entity.ProductEntity, int64, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetAllProducts")
	}

	var r0 []entity.ProductEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringProduct) ([]entity.ProductEntity, int64, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringProduct) []entity.ProductEntity); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringProduct) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringProduct) int64); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringProduct) error); ok {
		r3 = rf(ctx, query)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetHomeProducts provides a mock function with given fields: ctx, limit
func (_m *ProductRepositoryInterface) GetHomeProducts(ctx context.Context, limit int) ([]entity.ProductEntity, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetHomeProducts")
	}

	var r0 []entity.ProductEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]entity.ProductEntity, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []entity.ProductEntity); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, productID
func (_m *ProductRepositoryInterface) GetProductByID(ctx context.Context, productID int64) (*entity.ProductEntity, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 *entity.ProductEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.ProductEntity, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.ProductEntity); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVariantsByParentID provides a mock function with given fields: ctx, parentID
func (_m *ProductRepositoryInterface) GetVariantsByParentID(ctx context.Context, parentID int64) ([]entity.ProductEntity, error) {
	ret := _m.Called(ctx, parentID)

	if len(ret) == 0 {
		panic("no return value specified for GetVariantsByParentID")
	}

	var r0 []entity.ProductEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]entity.ProductEntity, error)); ok {
		return rf(ctx, parentID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []entity.ProductEntity); ok {
		r0 = rf(ctx, parentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, parentID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchProducts provides a mock function with given fields: ctx, query
func (_m *ProductRepositoryInterface) SearchProducts(ctx context.Context, query entity.QueryStringProduct) ([]entity.ProductEntity, int64, int64, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for SearchProducts")
	}

	var r0 []entity.ProductEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringProduct) ([]entity.ProductEntity, int64, int64, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringProduct) []entity.ProductEntity); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringProduct) int64); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringProduct) int64); ok {
		r2 = rf(ctx, query)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringProduct) error); ok {
		r3 = rf(ctx, query)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// UpdateProduct provides a mock function with given fields: ctx, product
func (_m *ProductRepositoryInterface) UpdateProduct(ctx context.Context, product entity.ProductEntity) (*entity.ProductEntity, error) {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProduct")
	}

	var r0 *entity.ProductEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ProductEntity) (*entity.ProductEntity, error)); ok {
		return rf(ctx, product)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.ProductEntity) *entity.ProductEntity); ok {
		r0 = rf(ctx, product)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ProductEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.ProductEntity) error); ok {
		r1 = rf(ctx, product)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductRepositoryInterface creates a new instance of ProductRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductRepositoryInterface {
	mock := &ProductRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
