// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "order-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// OrderServiceInterface is an autogenerated mock type for the OrderServiceInterface type
type OrderServiceInterface struct {
	mock.Mock
}

// CreateOrder provides a mock function with given fields: ctx, req
func (_m *OrderServiceInterface) CreateOrder(ctx context.Context, req entity.OrderEntity) (int64, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderEntity) (int64, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderEntity) int64); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.OrderEntity) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllCustomerOrders provides a mock function with given fields: ctx, queryString, accessToken
func (_m *OrderServiceInterface) GetAllCustomerOrders(ctx context.Context, queryString entity.QueryStringEntity, accessToken string) ([]entity.OrderEntity, int64, int64, error) {
	ret := _m.Called(ctx, queryString, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for GetAllCustomerOrders")
	}

	var r0 []entity.OrderEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringEntity, string) ([]entity.OrderEntity, int64, int64, error)); ok {
		return rf(ctx, queryString, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringEntity, string) []entity.OrderEntity); ok {
		r0 = rf(ctx, queryString, accessToken)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringEntity, string) int64); ok {
		r1 = rf(ctx, queryString, accessToken)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringEntity, string) int64); ok {
		r2 = rf(ctx, queryString, accessToken)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringEntity, string) error); ok {
		r3 = rf(ctx, queryString, accessToken)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetAllOrders provides a mock function with given fields: ctx, queryString
func (_m *OrderServiceInterface) GetAllOrders(ctx context.Context, queryString entity.QueryStringEntity) ([]entity.OrderEntity, int64, int64, error) {
	ret := _m.Called(ctx, queryString)

	if len(ret) == 0 {
		panic("no return value specified for GetAllOrders")
	}

	var r0 []entity.OrderEntity
	var r1 int64
	var r2 int64
	var r3 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringEntity) ([]entity.OrderEntity, int64, int64, error)); ok {
		return rf(ctx, queryString)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.QueryStringEntity) []entity.OrderEntity); ok {
		r0 = rf(ctx, queryString)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.QueryStringEntity) int64); ok {
		r1 = rf(ctx, queryString)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.QueryStringEntity) int64); ok {
		r2 = rf(ctx, queryString)
	} else {
		r2 = ret.Get(2).(int64)
	}

	if rf, ok := ret.Get(3).(func(context.Context, entity.QueryStringEntity) error); ok {
		r3 = rf(ctx, queryString)
	} else {
		r3 = ret.Error(3)
	}

	return r0, r1, r2, r3
}

// GetCustomerOrderByID provides a mock function with given fields: ctx, orderID
func (_m *OrderServiceInterface) GetCustomerOrderByID(ctx context.Context, orderID int64) (*entity.OrderEntity, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerOrderByID")
	}

	var r0 *entity.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.OrderEntity, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.OrderEntity); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByID provides a mock function with given fields: ctx, orderID
func (_m *OrderServiceInterface) GetOrderByID(ctx context.Context, orderID int64) (*entity.OrderEntity, error) {
	ret := _m.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByID")
	}

	var r0 *entity.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.OrderEntity, error)); ok {
		return rf(ctx, orderID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.OrderEntity); ok {
		r0 = rf(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOrderByOrderCode provides a mock function with given fields: ctx, code
func (_m *OrderServiceInterface) GetOrderByOrderCode(ctx context.Context, code string) (*entity.OrderEntity, error) {
	ret := _m.Called(ctx, code)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByOrderCode")
	}

	var r0 *entity.OrderEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.OrderEntity, error)); ok {
		return rf(ctx, code)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.OrderEntity); ok {
		r0 = rf(ctx, code)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.OrderEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, code)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusOrder provides a mock function with given fields: ctx, req
func (_m *OrderServiceInterface) UpdateStatusOrder(ctx context.Context, req entity.OrderEntity) error {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.OrderEntity) error); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewOrderServiceInterface creates a new instance of OrderServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderServiceInterface {
	mock := &OrderServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
