// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "order-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// ProductSnapshotRepositoryInterface is an autogenerated mock type for the ProductSnapshotRepositoryInterface type
type ProductSnapshotRepositoryInterface struct {
	mock.Mock
}

// GetByProductID provides a mock function with given fields: ctx, productID
func (_m *ProductSnapshotRepositoryInterface) GetByProductID(ctx context.Context, productID int64) (*entity.ProductSnapshotEntity, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductID")
	}

	var r0 *entity.ProductSnapshotEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.ProductSnapshotEntity, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.ProductSnapshotEntity); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.ProductSnapshotEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByProductIDs provides a mock function with given fields: ctx, productIDs
func (_m *ProductSnapshotRepositoryInterface) GetByProductIDs(ctx context.Context, productIDs []int64) ([]entity.ProductSnapshotEntity, error) {
	ret := _m.Called(ctx, productIDs)

	if len(ret) == 0 {
		panic("no return value specified for GetByProductIDs")
	}

	var r0 []entity.ProductSnapshotEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []int64) ([]entity.ProductSnapshotEntity, error)); ok {
		return rf(ctx, productIDs)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []int64) []entity.ProductSnapshotEntity); ok {
		r0 = rf(ctx, productIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.ProductSnapshotEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []int64) error); ok {
		r1 = rf(ctx, productIDs)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetInactive provides a mock function with given fields: ctx, productID
func (_m *ProductSnapshotRepositoryInterface) SetInactive(ctx context.Context, productID int64) error {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for SetInactive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upsert provides a mock function with given fields: ctx, product
func (_m *ProductSnapshotRepositoryInterface) Upsert(ctx context.Context, product entity.ProductSnapshotEntity) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.ProductSnapshotEntity) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProductSnapshotRepositoryInterface creates a new instance of ProductSnapshotRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductSnapshotRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductSnapshotRepositoryInterface {
	mock := &ProductSnapshotRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
