// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	entity "order-service/internal/core/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserSnapshotRepositoryInterface is an autogenerated mock type for the UserSnapshotRepositoryInterface type
type UserSnapshotRepositoryInterface struct {
	mock.Mock
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *UserSnapshotRepositoryInterface) GetByUserID(ctx context.Context, userID int64) (*entity.UserSnapshotEntity, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *entity.UserSnapshotEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*entity.UserSnapshotEntity, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *entity.UserSnapshotEntity); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.UserSnapshotEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upsert provides a mock function with given fields: ctx, user
func (_m *UserSnapshotRepositoryInterface) Upsert(ctx context.Context, user entity.UserSnapshotEntity) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, entity.UserSnapshotEntity) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserSnapshotRepositoryInterface creates a new instance of UserSnapshotRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserSnapshotRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserSnapshotRepositoryInterface {
	mock := &UserSnapshotRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
